[JS] bump: (deps-dev): Bump the development group in /js with 3 updates (#1475)
#minor Bumps the development group in /js with 3 updates:
[mocha](https://github.com/mochajs/mocha),
[@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node)
and [tsc-watch](https://github.com/gilamran/tsc-watch).

Updates `mocha` from 10.3.0 to 10.4.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/mochajs/mocha/releases">mocha's
releases</a>.</em></p>
<blockquote>
<h2>v10.4.0</h2>
<h2>10.4.0 / 2024-03-26</h2>
<h3>:tada: Enhancements</h3>
<ul>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/4829">#4829</a>
feat: include <code>.cause</code> stacks in the error stack traces (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/4985">#4985</a>
feat: add file path to xunit reporter (<a
href="https://github.com/bmish"><strong><code>@​bmish</code></strong></a>)</li>
</ul>
<h3>:bug: Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5074">#5074</a>
fix: harden error handling in <code>lib/cli/run.js</code> (<a
href="https://github.com/stalet"><strong><code>@​stalet</code></strong></a>)</li>
</ul>
<h3>:nut_and_bolt: Other</h3>
<ul>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5077">#5077</a>
chore: add mtfoley/pr-compliance-action (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5060">#5060</a>
chore: migrate ESLint config to flat config (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5095">#5095</a>
chore: revert <a
href="https://redirect.github.com/mochajs/mocha/pull/5069">#5069</a> to
restore Netlify builds (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5097">#5097</a>
docs: add sponsored to sponsorship link rels (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5093">#5093</a>
chore: add 'status: in triage' label to issue templates and docs (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5083">#5083</a>
docs: fix CHANGELOG.md headings to start with a root-level h1 (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5100">#5100</a>
chore: fix header generation and production build crashes (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5104">#5104</a>
chore: bump ESLint ecmaVersion to 2020 (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5116">#5116</a>
fix: eleventy template builds crash with 'unexpected token at &quot;:
string, msg...&quot;' (<a
href="https://github.com/LcsK"><strong><code>@​LcsK</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/4869">#4869</a>
docs: fix documentation concerning glob expansion on UNIX (<a
href="https://github.com/binki"><strong><code>@​binki</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5122">#5122</a>
test: fix xunit integration test (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5123">#5123</a>
chore: activate dependabot for workflows (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5125">#5125</a>
build(deps): bump the github-actions group with 2 updates (<a
href="https://github.com/dependabot"><strong><code>@​dependabot</code></strong></a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/mochajs/mocha/blob/master/CHANGELOG.md">mocha's
changelog</a>.</em></p>
<blockquote>
<h2>10.4.0 / 2024-03-26</h2>
<h3>:tada: Enhancements</h3>
<ul>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/4829">#4829</a>
feat: include <code>.cause</code> stacks in the error stack traces (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/4985">#4985</a>
feat: add file path to xunit reporter (<a
href="https://github.com/bmish"><strong><code>@​bmish</code></strong></a>)</li>
</ul>
<h3>:bug: Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5074">#5074</a>
fix: harden error handling in <code>lib/cli/run.js</code> (<a
href="https://github.com/stalet"><strong><code>@​stalet</code></strong></a>)</li>
</ul>
<h3>:nut_and_bolt: Other</h3>
<ul>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5077">#5077</a>
chore: add mtfoley/pr-compliance-action (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5060">#5060</a>
chore: migrate ESLint config to flat config (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5095">#5095</a>
chore: revert <a
href="https://redirect.github.com/mochajs/mocha/pull/5069">#5069</a> to
restore Netlify builds (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5097">#5097</a>
docs: add sponsored to sponsorship link rels (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5093">#5093</a>
chore: add 'status: in triage' label to issue templates and docs (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5083">#5083</a>
docs: fix CHANGELOG.md headings to start with a root-level h1 (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5100">#5100</a>
chore: fix header generation and production build crashes (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5104">#5104</a>
chore: bump ESLint ecmaVersion to 2020 (<a
href="https://github.com/JoshuaKGoldberg"><strong><code>@​JoshuaKGoldberg</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5116">#5116</a>
fix: eleventy template builds crash with 'unexpected token at &quot;:
string, msg...&quot;' (<a
href="https://github.com/LcsK"><strong><code>@​LcsK</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/4869">#4869</a>
docs: fix documentation concerning glob expansion on UNIX (<a
href="https://github.com/binki"><strong><code>@​binki</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5122">#5122</a>
test: fix xunit integration test (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5123">#5123</a>
chore: activate dependabot for workflows (<a
href="https://github.com/voxpelli"><strong><code>@​voxpelli</code></strong></a>)</li>
<li><a
href="https://redirect.github.com/mochajs/mocha/pull/5125">#5125</a>
build(deps): bump the github-actions group with 2 updates (<a
href="https://github.com/dependabot"><strong><code>@​dependabot</code></strong></a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/mochajs/mocha/commit/ffd9557ee291047f7beef71a24796ea2da256614"><code>ffd9557</code></a>
Release v10.4.0</li>
<li><a
href="https://github.com/mochajs/mocha/commit/7ac67f3735b1ba6b1e1565ab9136d83c50f58abf"><code>7ac67f3</code></a>
build(deps): bump the github-actions group with 2 updates (<a
href="https://redirect.github.com/mochajs/mocha/issues/5125">#5125</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/7a2781c17d4924c620ce5b31c4aab6c88bed72ef"><code>7a2781c</code></a>
chore: activate dependabot for workflows (<a
href="https://redirect.github.com/mochajs/mocha/issues/5123">#5123</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/97dcbb28225105f16e90d2180aa2be3386d7ec1a"><code>97dcbb2</code></a>
fix: harden error handling in <code>lib/cli/run.js</code> (<a
href="https://redirect.github.com/mochajs/mocha/issues/5074">#5074</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/6f3f45e587a17463b75047631152429fa14b82a3"><code>6f3f45e</code></a>
fix: xunit integration test (<a
href="https://redirect.github.com/mochajs/mocha/issues/5122">#5122</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/a5b565289b40a839af086b13fb369e04e205ed4b"><code>a5b5652</code></a>
docs: fix documentation concerning glob expansion on UNIX (<a
href="https://redirect.github.com/mochajs/mocha/issues/4869">#4869</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/efbb147590dfd7ff290de40a9930b07334784054"><code>efbb147</code></a>
feat: add file path to xunit reporter (<a
href="https://redirect.github.com/mochajs/mocha/issues/4985">#4985</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/a2e600d70f4d7ca6ba8741ebe8c70cfec438ef1b"><code>a2e600d</code></a>
fix: closes <a
href="https://redirect.github.com/mochajs/mocha/issues/5115">#5115</a>
(<a
href="https://redirect.github.com/mochajs/mocha/issues/5116">#5116</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/37358738260cfae7c244c157aee21654f2b588f2"><code>3735873</code></a>
feat: include <code>.cause</code> stacks in the error stack traces (<a
href="https://redirect.github.com/mochajs/mocha/issues/4829">#4829</a>)</li>
<li><a
href="https://github.com/mochajs/mocha/commit/b88978deb3c12f9b95502828f6ac29ebe8be85ef"><code>b88978d</code></a>
chore: bump ESLint ecmaVersion to 2020 (<a
href="https://redirect.github.com/mochajs/mocha/issues/5104">#5104</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/mochajs/mocha/compare/v10.3.0...v10.4.0">compare
view</a></li>
</ul>
</details>
<details>
<summary>Maintainer changes</summary>
<p>This version was pushed to npm by <a
href="https://www.npmjs.com/~voxpelli">voxpelli</a>, a new releaser for
mocha since your current version.</p>
</details>
<br />

Updates `@types/node` from 20.11.30 to 20.12.2
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/node">compare
view</a></li>
</ul>
</details>
<br />

Updates `tsc-watch` from 6.0.4 to 6.2.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/gilamran/tsc-watch/releases">tsc-watch's
releases</a>.</em></p>
<blockquote>
<h2>feature: Using prepublish</h2>
<p>No release notes provided.</p>
<p>feature: --noEmit. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></p>
<p>fix: error TS6369: Option '--build' must be the first command line
argument. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a> for the
PR</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/gilamran/tsc-watch/blob/master/CHANGELOG.md">tsc-watch's
changelog</a>.</em></p>
<blockquote>
<h2>v6.2.0 - 28/03/2024</h2>
<ul>
<li>feature: Using prepublish. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
</ul>
<h2>v6.1.0 - 27/03/2024</h2>
<ul>
<li>feature: --noEmit. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
</ul>
<h2>v6.0.5 - 27/03/2024</h2>
<ul>
<li>fix: error TS6369: Option '--build' must be the first command line
argument. thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/321fde98400a46444469afa051ef7189f10e7c9a"><code>321fde9</code></a>
6.2.0</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/0b82c957ade1e30522e35e71dce59cae336423f6"><code>0b82c95</code></a>
Add prepublish feature</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/34f90235bf83803bf7ad1b6ed715211d095618d4"><code>34f9023</code></a>
Merge pull request <a
href="https://redirect.github.com/gilamran/tsc-watch/issues/168">#168</a>
from llllvvuu/fix/prepublishOnly</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/56b0f30ccf2dccd8a85c0da91c9ac8d34ab639a6"><code>56b0f30</code></a>
build: run build in prepublishOnly</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/3f879777db65c35ccd459283b0ba1db25cb05ecc"><code>3f87977</code></a>
6.1.0</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/e3c9e203bbcd405c4a67a4ba3a8f23c2982c6a47"><code>e3c9e20</code></a>
Add --noEmit feature, thanks to <a
href="https://github.com/llllvvuu"><code>@​llllvvuu</code></a></li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/673fcaf9f5eff7973ee6cbf4c5001c57740f78f4"><code>673fcaf</code></a>
Merge pull request <a
href="https://redirect.github.com/gilamran/tsc-watch/issues/167">#167</a>
from llllvvuu/feat/on_emit</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/1c266ae26fb1dd2e1206f93cb0899909bb63262d"><code>1c266ae</code></a>
fix ascii art</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/37cd23be9aff87f74471e1cc407ff9495f26f7d5"><code>37cd23b</code></a>
Update README.md</li>
<li><a
href="https://github.com/gilamran/tsc-watch/commit/13653cc40c60203511e09c9dc0159e7a066237e5"><code>13653cc</code></a>
Update README.md</li>
<li>Additional commits viewable in <a
href="https://github.com/gilamran/tsc-watch/compare/v6.0.4...v6.2.0">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>